version: "3"

services:

  jupyter:

    image: geopython/workshop:latest

    container_name: geopython_ws_jupyter

    ports:
      - "8888:8888"

    volumes:
      - ./jupyter/content:/jupyter/content:rw

  pygeoapi:
    container_name: geopython_ws_pygeoapi
    image: geopython/pygeoapi:latest
    ports:
      - 5000:80

  pycsw:
    container_name: geopython_ws_pycsw
    image: geopython/pycsw:latest
    ports:
      - 8001:8000
