version: "3"

services:
  jupyter:
    container_name: geopython-workshop-jupyter
    image: geopython/geopython-workshop:latest
    ports:
      - 8888:8888
    volumes:
      - ./jupyter/content:/jupyter/content:rw

  pygeoapi:
    container_name: geopython-workshop-pygeoapi
    image: geopython/pygeoapi:latest
    ports:
      - 5000:80
    volumes:
      - ./services/pygeoapi-config.yml:/pygeoapi/local.config.yml:ro
      - ./jupyter/content/data:/jupyter/content/data:ro

  pycsw:
    container_name: geopython-workshop-pycsw
    image: geopython/pycsw:latest
    ports:
      - 8001:8000
    volumes:
      - ./jupyter/content/data:/jupyter/content/data:ro
      - ./services/pycsw-config.cfg:/etc/pycsw/pycsw.cfg:ro

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
