site_name: Doing Geospatial in Python
site_description: Doing Geospatial in Python is a workshop on performing common GIS/geospatial tasks using Python geospatial tools.
site_author: the Doing Geospatial in Python Team
copyright: Copyright (c) 2019 the Doing Geospatial in Python Team
site_url: https://geopython.github.io/geopython-workshop
repo_url: https://github.com/geopython/geopython-workshop
docs_dir: docs

nav:
    - Home: index.md
    - Workshop:
      - Introduction: introduction.md
      - Data:
        - Vector Data: data/vector.md
        - Raster Data: data/raster.md
      - Metadata: metadata.md
      - Services:
        - OGC Web Services: services/ogc-web-services.md
        - Publishing Data: services/publishing-data.md
        - Publishing Metadata: services/publishing-metadata.md
        - Publishing Processes: services/publishing-processes.md
      - Emerging Technology and Trends: emerging-technology-and-trends.md
      - Resources: resources.md
      - Conclusion: conclusion.md
    - License: license.md

theme: slate

edit_uri: edit/foss4g-2019/workshop/docs

plugins:
    - search
